### ISSUE TITLE
Add GUI for gaia analyses

### ISSUE THREAD

**Issue by mbertrand** [OpenDataAnalytics/gaia_minerva#1]
Currently, gaia analyses can only be run by submitting a process in JSON format to the girder API (as described in README).  Need a front-end for users to select which analysis to run on which datasets.  The user input will be converted to gaia JSON and submitted to the API.
- User should be able to select one or more vector datasets (geojson, wms - if the wms layer is from an approved server as determined in the server/conf/gaia_minerva.cfg file).
- User should be able to select among any processes which take vector data as input and produce vector data as output (including processes from any loaded gaia plugin).
- Raster support will come later.
- A new 'GaiaAnalysisWidget' will need to be created along with associated JS, CSS, etc to contain the GUI.  An example of existing analysis widgets + code is 'BSVE Search' and 'MMWR':
  - To enable these plugins, run:
    
    ```
    python import_analyses.py --username <username> --password <password> --host <girder_host> --port <girder_port> --path ../analyses/bsve/
    ```
  - The code for existing widgets is located here, use these as a template?
    - https://github.com/Kitware/minerva/blob/master/web_external/templates/widgets/bsveSearchWidget.jade
    - https://github.com/Kitware/minerva/blob/master/web_external/js/views/widgets/MmwrImportDataWidget.js
    - https://github.com/Kitware/minerva/blob/master/web_external/templates/widgets/bsveSearchWidget.jade
    - https://github.com/Kitware/minerva/blob/master/web_external/templates/widgets/mmwrImportDataWidget.jade
  - Ideally the widget code for Gaia would exist in the gaia_minerva repo, under a web_external folder, and be incorporated into minerva during the build process.

Related to Gaia issue https://github.com/OpenDataAnalytics/gaia/issues/72

**Comment by mbertrand** [comment]
@aashish24 Could you review?

**Comment by mbertrand** [comment]
PS Some further backend code development may be necessary to be able to determine from the front-end which kinds of Gaia inputs/outputs are required & generated by which Gaia processes.

**Comment by mbertrand** [comment]
@aashish24, the UI is ready.  Here is what the widget looks like:

![screen shot 2016-10-14 at 5 14 06 pm](https://cloud.githubusercontent.com/assets/187676/19402901/dcb72860-9231-11e6-8943-541dcd92a91c.png)

After submitting, the job is run, and once finished the output geojson dataset is available for viewing:

![screen shot 2016-10-14 at 5 15 00 pm](https://cloud.githubusercontent.com/assets/187676/19402907/e1f55d38-9231-11e6-9642-1a1a66f0d1c8.png)

Currently the UI will only work with GeoJSON datasets.  Essam will work on including WMS datasets next.

One issue I've noticed is that the Minerva UI cannot render certain Gaia output datasets; a javascript error results.  The geojson data itself is fine (I tested it in other apps and it validated and displayed) so it may be an issue with the item metadata, I'll look into it next week.

This plugin depends on Gaia PR https://github.com/OpenDataAnalytics/gaia/pull/77

**Comment by aashish24** [comment]
> Currently the UI will only work with GeoJSON datasets. Essam will work on including WMS datasets next.
> 
> One issue I've noticed is that the Minerva UI cannot render certain Gaia output datasets; a javascript error results. The geojson data itself is fine (I tested it in other apps and it validated and displayed) so it may be an issue with the item metadata, I'll look into it next week.
> 
> This plugin depends on Gaia PR OpenDataAnalytics/gaia#77

this is awesome guys :clap: :clap:

**Comment by mbertrand** [comment]
@aashish24,  the rendering issue I experienced originates in the geojs code for the release version bundled with minerva (v0.10.1).  I could duplicate the problem in the 'GeoJSON file reader' example with the geojs v0.10.1 code.  The problem does not occur with the latest geojs release (0.10.3).
